apiVersion: 1

datasources:
  - name: InfluxDB-CityGrid
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: citygrid
      defaultBucket: citygrid
      tlsSkipVerify: true
    secureJsonData:
      token: citygrid-token-2024
    isDefault: true
    editable: true
