apiVersion: 1

datasources:
  - name: InfluxDB-CityGrid
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: $CITYGRID_INFLUX_ORG
      defaultBucket: $CITYGRID_INFLUX_BUCKET
      tlsSkipVerify: true
    secureJsonData:
      token: $CITYGRID_INFLUX_TOKEN
    isDefault: true
    editable: false
