/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as DecisoesRouteImport } from './routes/decisoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZonaIdRouteImport } from './routes/zona.$id'

const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisoesRoute = DecisoesRouteImport.update({
  id: '/decisoes',
  path: '/decisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonaIdRoute = ZonaIdRouteImport.update({
  id: '/zona/$id',
  path: '/zona/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/decisoes': typeof DecisoesRoute
  '/mapa': typeof MapaRoute
  '/zona/$id': typeof ZonaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/decisoes': typeof DecisoesRoute
  '/mapa': typeof MapaRoute
  '/zona/$id': typeof ZonaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/decisoes': typeof DecisoesRoute
  '/mapa': typeof MapaRoute
  '/zona/$id': typeof ZonaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/decisoes' | '/mapa' | '/zona/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/decisoes' | '/mapa' | '/zona/$id'
  id: '__root__' | '/' | '/decisoes' | '/mapa' | '/zona/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DecisoesRoute: typeof DecisoesRoute
  MapaRoute: typeof MapaRoute
  ZonaIdRoute: typeof ZonaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisoes': {
      id: '/decisoes'
      path: '/decisoes'
      fullPath: '/decisoes'
      preLoaderRoute: typeof DecisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona/$id': {
      id: '/zona/$id'
      path: '/zona/$id'
      fullPath: '/zona/$id'
      preLoaderRoute: typeof ZonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DecisoesRoute: DecisoesRoute,
  MapaRoute: MapaRoute,
  ZonaIdRoute: ZonaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
