/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApresentacaoRouteImport } from './routes/apresentacao'
import { Route as ApresentadorRouteImport } from './routes/apresentador'
import { Route as DecisoesRouteImport } from './routes/decisoes'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ParticiparCodigoRouteImport } from './routes/participar.$codigo'
import { Route as ZonaIdRouteImport } from './routes/zona.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentacaoRoute = ApresentacaoRouteImport.update({
  id: '/apresentacao',
  path: '/apresentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApresentadorRoute = ApresentadorRouteImport.update({
  id: '/apresentador',
  path: '/apresentador',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisoesRoute = DecisoesRouteImport.update({
  id: '/decisoes',
  path: '/decisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticiparCodigoRoute = ParticiparCodigoRouteImport.update({
  id: '/participar/$codigo',
  path: '/participar/$codigo',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonaIdRoute = ZonaIdRouteImport.update({
  id: '/zona/$id',
  path: '/zona/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/apresentador': typeof ApresentadorRoute
  '/decisoes': typeof DecisoesRoute
  '/mapa': typeof MapaRoute
  '/participar/$codigo': typeof ParticiparCodigoRoute
  '/zona/$id': typeof ZonaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/apresentador': typeof ApresentadorRoute
  '/decisoes': typeof DecisoesRoute
  '/mapa': typeof MapaRoute
  '/participar/$codigo': typeof ParticiparCodigoRoute
  '/zona/$id': typeof ZonaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apresentacao': typeof ApresentacaoRoute
  '/apresentador': typeof ApresentadorRoute
  '/decisoes': typeof DecisoesRoute
  '/mapa': typeof MapaRoute
  '/participar/$codigo': typeof ParticiparCodigoRoute
  '/zona/$id': typeof ZonaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apresentacao'
    | '/apresentador'
    | '/decisoes'
    | '/mapa'
    | '/participar/$codigo'
    | '/zona/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apresentacao'
    | '/apresentador'
    | '/decisoes'
    | '/mapa'
    | '/participar/$codigo'
    | '/zona/$id'
  id:
    | '__root__'
    | '/'
    | '/apresentacao'
    | '/apresentador'
    | '/decisoes'
    | '/mapa'
    | '/participar/$codigo'
    | '/zona/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApresentacaoRoute: typeof ApresentacaoRoute
  ApresentadorRoute: typeof ApresentadorRoute
  DecisoesRoute: typeof DecisoesRoute
  MapaRoute: typeof MapaRoute
  ParticiparCodigoRoute: typeof ParticiparCodigoRoute
  ZonaIdRoute: typeof ZonaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentacao': {
      id: '/apresentacao'
      path: '/apresentacao'
      fullPath: '/apresentacao'
      preLoaderRoute: typeof ApresentacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apresentador': {
      id: '/apresentador'
      path: '/apresentador'
      fullPath: '/apresentador'
      preLoaderRoute: typeof ApresentadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisoes': {
      id: '/decisoes'
      path: '/decisoes'
      fullPath: '/decisoes'
      preLoaderRoute: typeof DecisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participar/$codigo': {
      id: '/participar/$codigo'
      path: '/participar/$codigo'
      fullPath: '/participar/$codigo'
      preLoaderRoute: typeof ParticiparCodigoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona/$id': {
      id: '/zona/$id'
      path: '/zona/$id'
      fullPath: '/zona/$id'
      preLoaderRoute: typeof ZonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApresentacaoRoute: ApresentacaoRoute,
  ApresentadorRoute: ApresentadorRoute,
  DecisoesRoute: DecisoesRoute,
  MapaRoute: MapaRoute,
  ParticiparCodigoRoute: ParticiparCodigoRoute,
  ZonaIdRoute: ZonaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
